language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pm90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pm90/react-test npm run test

after_success:
  - docker build -t pm90/multi-client ./client
  - docker build -t pm90/multi-server ./server
  - docker build -t pm90/multi-worker ./worker
  - docker build -t pm90/multi-nginx ./nginx

  # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

  - docker push pm90/multi-client
  - docker push pm90/multi-server
  - docker push pm90/multi-worker
  - docker push pm90/multi-nginx

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "react-example-travis"
#   env: "ReactExampleTravis-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-277367360328"
#   bucket_path: "react-example-travis"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY